repos:
  # Хук для форматирования с Ruff
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        args: [ --fix, --exit-zero-on-fix ]
        language: system
        types: [ python ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0  # Указываем конкретную версию mypy
    hooks:
      - id: mypy
        args: [ --config-file=mypy.ini ]  # Указываем mypy.ini вместо pyproject.toml
        files: ^(?!tests/).*$  # Исключаем папку "tests"
        additional_dependencies:
          - "pydantic>=2.6.0"  # Указываем версию pydantic
          - "pydantic[mypy]"   # Устанавливаем pydantic с поддержкой mypy плагина

  # Хук для запуска тестов с pytest
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system  # Использует локально установленный pytest
        pass_filenames: false  # Не передавать имена файлов, запускать все тесты
        always_run: true  # Запускать всегда, даже если нет изменений