repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix --exit-zero
        language: system
        types: [ python ]
        pass_filenames: false  # Отключаем передачу имен файлов

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [ --config-file=mypy.ini ]
        files: ^(?!tests/).*$
        additional_dependencies:
          - "pydantic>=2.6.0"
          - "pydantic[mypy]"

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true