"""add uniq on title

Revision ID: f0ed9289905e
Revises: 55cd5d41c17c
Create Date: 2025-03-23 01:44:12.854125

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0ed9289905e"
down_revision: Union[str, None] = "55cd5d41c17c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "projects", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="unique")
    # ### end Alembic commands ###
